server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    hostname: gateway-service
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    metadata-map:
      "management.port": 8222

management:
  endpoints:
    web:
      exposure:
        include: health,info


spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server:8888
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: user_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/** # Capture le chemin envoyé par le frontend
        # Ajoutez les autres routes (quiz, reward) de la même manière
        - id: quiz_route
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/api/quiz/**
        - id: reward_route
          uri: lb://REWARD-SERVICE
          predicates:
            - Path=/api/score/**
  security:
    user:
      name: ""
      password: ""


security:
  jwt:
    secret: "MaCleSuperSecreteQuiFaitPlusDe32Caractères1234"
    expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG




